name: "KNX Sentinel 2"
version: "0.1.3"
slug: "knx_sentinel_2"
description: "KNX Sentinel 2 - Developed by Manara Engineering"
url: "https://www.manara.co.in"
startup: application
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  log_level: "info"
  knx_host: ""
  knx_port: 3671
  knx_type: "AUTOMATIC"
schema:
  log_level: "str"
  knx_host: "str"
  knx_port: "int"
  knx_type: "list(AUTOMATIC|TUNNELING|ROUTING)"
ports:
  8000/tcp: 8000
full_access: true
